# Fix iOS Build: Deployment Target 15.0
platform :ios, '15.0'

# Flutter's pod helper
load File.join(File.dirname(File.realpath(__FILE__)), 'Flutter', 'pod_helper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      config.build_settings['DEVELOPMENT_TEAM'] = '1234567890'
      config.build_settings['CODE_SIGN_STYLE'] = 'Automatic'
    end
  end
end
